version: '3.5'
services:
  server:
    build: ../05
    container_name: server
  proxy_nginx:
    image: nginx
    container_name: proxy_nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf